import { Router } from 'express';
import * as a from '../controllers/admin.controller.js';
import uploadRoutes from './upload.routes.js';
import { requireAdmin } from '../middlewares/auth.js';
import { validate } from '../middlewares/validate.js';
import { loginLimiter } from '../middlewares/rateLimit.js';
import { uploadFiles } from '../middlewares/upload.middleware.js';
const r = Router();
r.post('/auth/login', loginLimiter, validate(a.loginSchema), a.login);
r.use(requireAdmin);
r.post('/auth/logout', a.logout); r.get('/me', a.me); r.put('/me/password', validate(a.passwordSchema), a.changePassword);
r.get('/stats', a.stats);
r.get('/visitors', a.listVisitors); r.get('/visitors/summary', a.visitorSummary); r.get('/visitors/:visitorId', a.visitorDetail);
r.get('/submissions', a.listSubmissions); r.post('/submissions/bulk', a.bulkSubmissions); r.get('/submissions/:id', a.submissionDetail); r.patch('/submissions/:id', a.updateSubmission);
r.get('/leads', a.listSubmissions);
r.get('/audits', a.listAudits); r.get('/audits/:id', a.auditDetail);
r.get('/contacts', a.listContacts); r.patch('/contacts/:id', a.updateContact);
r.get('/chats', a.listChats); r.get('/chats/:sessionId', a.chatDetail);
r.get('/files', a.listFiles); r.delete('/files/:id', a.deleteFile); r.use('/upload', uploadRoutes);
r.get('/schemes/export', a.exportSchemes);
r.get('/schemes', a.listSchemes); r.post('/schemes', a.createScheme);
r.post('/schemes/import/preview', ...uploadFiles(['schemeImport']), a.previewSchemeImport);
r.post('/schemes/import', ...uploadFiles(['schemeImport']), a.importSchemes);
r.patch('/schemes/:id/publish', a.publishScheme);
r.get('/schemes/:id', a.getScheme); r.put('/schemes/:id', a.updateScheme); r.delete('/schemes/:id', a.deleteScheme);
r.get('/rules', a.getRulesCtl); r.put('/rules', a.putRules); r.post('/rules/reset', a.resetRules); r.post('/rules/simulate', a.simulateRules);
r.get('/lookups', a.listLookups); r.put('/lookups/:key', a.putLookup);
r.get('/settings', a.getSettings); r.put('/settings', a.putSettings);
r.get('/reports/:name', a.report);
export default r;
