import express from 'express';
import helmet from 'helmet';
import compression from 'compression';
import cookieParser from 'cookie-parser';
import corsMw from './config/cors.js';
import { UPLOAD_ROOT } from './config/multer.js';
import { sanitize } from './middlewares/validate.js';
import { apiLimiter } from './middlewares/rateLimit.js';
import { trackVisitor } from './middlewares/trackVisitor.js';
import { notFound, errorHandler } from './middlewares/error.js';
import publicRoutes from './routes/public.routes.js';
import trackRoutes from './routes/track.routes.js';
import chatRoutes from './routes/chat.routes.js';
import adminRoutes from './routes/admin.routes.js';
const app = express();
app.set('trust proxy', 1);
app.use(helmet({ crossOriginResourcePolicy: { policy: 'cross-origin' } }), corsMw, compression(), express.json({ limit: '1mb' }), cookieParser(), sanitize);
app.use('/uploads', express.static(UPLOAD_ROOT, { dotfiles: 'deny', index: false, maxAge: '7d', setHeaders: (res) => res.setHeader('X-Content-Type-Options', 'nosniff') }));
app.get('/health', (_q, res) => res.json({ ok: true }));
app.use('/api/v1', apiLimiter, trackVisitor);
app.use('/api/v1/public', publicRoutes);
app.use('/api/v1/track', trackRoutes);
app.use('/api/v1/chat', chatRoutes);
app.use('/api/v1/admin', adminRoutes);
app.use(notFound, errorHandler);
export default app;
